; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:full_arm]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
upload_speed = 921600
build_src_filter = +<*.cpp> -<main_single.cpp> -<main_calibration.cpp> -<main_servo_test.cpp>
lib_deps =
    adafruit/Adafruit BNO08x @ ^1.2.5
    ArduinoEigen
    ESP32Servo 

[env:single_servo]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
upload_speed = 921600
build_src_filter = +<*.cpp> -<main.cpp> -<main_calibration.cpp> -<main_servo_test.cpp>
lib_deps =
    adafruit/Adafruit BNO08x @ ^1.2.5
    ArduinoEigen
    ESP32Servo 

[env:calibration]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
upload_speed = 921600
build_src_filter = +<*.cpp> -<main.cpp> -<main_single.cpp> -<main_servo_test.cpp>
lib_deps =
    adafruit/Adafruit BNO08x @ ^1.2.5
    ArduinoEigen
    ESP32Servo 

[env:servo_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
upload_speed = 921600
build_src_filter = +<*.cpp> -<main.cpp> -<main_single.cpp> -<main_calibration.cpp>
lib_deps =
    ESP32Servo 